### ISSUE TITLE
Issue Regarding Interest Payouts.

### ISSUE THREAD

**Issue by Antdog319** [TheGameFreak666/iConomy-7#4]
Version:

[INFO] This server is running CraftBukkit version git-Bukkit-4c3da3f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

Console Error:

[WARN] Exception in thread "Timer-1"
[WARN] java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[WARN] at com.iCo6.system.Interest.run(Interest.java:31)
[WARN] at java.util.TimerThread.mainLoop(Unknown Source)
[WARN] at java.util.TimerThread.run(Unknown Source)

Config regarding interest in case I did something wrong there:

Interest:
Enabled: true

Online: true

Announce:
  Enabled: true

Interval:
  Seconds: 60

Amount:
   Cutoff: 0.0

  Percent: 0.0

  Maximum: 0.10
  Minimum: 0.01

Greatly appreciate any follow up on this issue.

**Comment by TheGameFreak666** [comment]
Are you using a snapshot? Please don't, it is bugging out when you use one due to its unstability.
