### ISSUE TITLE
mysql.jar

### ISSUE THREAD

**Issue by CCCCarsten** [TheGameFreak666/iConomy-7#8]
Hi,
what does that always mean?? How can I stop that?

11.11 21:35:24 [Server] INFO Hello, I'm Nijikokun. Yes, this is an April Fools joke, but '/money top' was fixed! Enjoy :) - Rare Version!
11.11 21:35:24 [Server] INFO Enabled (4 ms)
11.11 21:35:24 [Server] INFO Finished Downloading.
11.11 21:35:24 [Server] INFO Error Downloading File: java.net.ConnectException: Connection timed out
11.11 21:33:17 [Server] INFO + mysql.jar (-1 B)
11.11 21:31:09 [Server] INFO Downloading mysql.jar...

Ciao, Carsten

**Comment by hwnd32** [comment]
download archive from https://dev.mysql.com/downloads/connector/j/  and get .jar file
rename it to mysql.jar  and place to minecraft service directory(LIB!): /home/USER_NAME/minecraft/lib

**Comment by CCCCarsten** [comment]
Thank you very much!
